apiVersion: v1
kind: Service
metadata:
  name: mira-website
  labels:
    app.kubernetes.io/name: mira-website
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mira
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mira-website
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
