// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.tilt-us.com' | (string & {});
};

export type UpdateUsernameRequest = {
    username: string;
};

export type UserProfileResponse = {
    subject?: string;
    publicId?: number;
    email?: string;
    preferredUsername?: string;
    displayName?: string;
    tagId?: string;
    level?: number;
    avatarUrl?: string;
    avatarRightsConsented?: boolean;
    avatarRightsConsentedAt?: string;
    authorities?: Array<string>;
};

export type UpdateTagIdRequest = {
    tagId: string;
};

export type ClientSettingsFolderRequest = {
    name: string;
    moveHereWhen?: string;
    friendPublicIds?: Array<number>;
};

export type UpdateClientSettingsRequest = {
    resolution?: string;
    uiScale?: number;
    accentColor?: string;
    background?: string;
    clientAnimation?: string;
    language?: string;
    chatPosition?: string;
    screenMode?: string;
    allowFriendRequest?: string;
    showEmailPublic?: boolean;
    useFriendColors?: boolean;
    folders?: Array<ClientSettingsFolderRequest>;
};

export type ClientSettingsFolderResponse = {
    name?: string;
    moveHereWhen?: string;
    friendPublicIds?: Array<number>;
};

export type ClientSettingsResponse = {
    resolution?: string;
    uiScale?: number;
    accentColor?: string;
    background?: string;
    clientAnimation?: string;
    language?: string;
    chatPosition?: string;
    screenMode?: string;
    allowFriendRequest?: string;
    showEmailPublic?: boolean;
    useFriendColors?: boolean;
    folders?: Array<ClientSettingsFolderResponse>;
};

export type ClientSettingsFolderUpsertRequest = {
    moveHereWhen?: string;
    friendPublicIds?: Array<number>;
};

export type ClientSettingsFolderRenameRequest = {
    name: string;
};

export type ClientSettingsFolderOrderRequest = {
    folderNames: Array<string>;
};

export type UpdateLevelRequest = {
    level: number;
};

export type RegistrationRequest = {
    email: string;
    password: string;
    displayName: string;
};

export type RegistrationResponse = {
    status?: string;
    message?: string;
};

export type IncreaseLevelRequest = {
    amount: number;
};

export type AvatarRightsConsentResponse = {
    isConsented?: boolean;
    consentedAt?: string;
};

export type FriendActionRequest = {
    targetPublicId: number;
};

export type FriendRequestResponse = {
    id?: number;
    requester?: FriendUserResponse;
    addressee?: FriendUserResponse;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type FriendUserResponse = {
    publicId?: number;
    displayName?: string;
    email?: string;
    tagId?: string;
    avatarUrl?: string;
    avatarRightsConsented?: boolean;
    avatarRightsConsentedAt?: string;
};

export type PublicClientSettingsResponse = {
    publicId?: number;
    accentColor?: string;
    showEmailPublic?: boolean;
};

export type UserSearchResponse = {
    users?: Array<FriendUserResponse>;
};

export type PublicUsersResponse = {
    users?: Array<FriendUserResponse>;
};

export type LoginOptionsResponse = {
    providers?: Array<string>;
};

export type HealthResponse = {
    status?: string;
    service?: string;
};

export type FriendsResponse = {
    friends?: Array<FriendUserResponse>;
};

export type FriendRequestsResponse = {
    incoming?: Array<FriendRequestResponse>;
    outgoing?: Array<FriendRequestResponse>;
};

export type LoginAttemptItemResponse = {
    id?: string;
    occurredAt?: string;
    sessionId?: string;
    deviceType?: string;
    sourceIp?: string;
    userAgent?: string;
    reason?: string;
};

export type LoginAttemptResponse = {
    hasRecentConflictAttempts?: boolean;
    attempts?: Array<LoginAttemptItemResponse>;
};

export type AuthDebugResponse = {
    subject?: string;
    issuer?: string;
    email?: string;
    preferredUsername?: string;
    displayName?: string;
    picture?: string;
    avatarUrl?: string;
    discordUserId?: string;
    discordAvatar?: string;
    audiences?: Array<string>;
    authorities?: Array<string>;
};

export type DeleteUserRequest = {
    email: string;
};

export type UpdateUserStatusRequest = {
    status: 'OFFLINE' | 'ONLINE' | 'AFK' | 'IN_LOBBY' | 'IN_QUEUE' | 'CHAMPION_SELECTION' | 'IN_GAME' | 'SPECTATE';
    mode?: string;
};

export type UserStatusSnapshot = {
    publicId?: number;
    status?: 'OFFLINE' | 'ONLINE' | 'AFK' | 'IN_LOBBY' | 'IN_QUEUE' | 'CHAMPION_SELECTION' | 'IN_GAME' | 'SPECTATE';
    mode?: string;
    updatedAt?: string;
};

export type UpdateLobbyRolesRequest = {
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
};

export type LobbyMemberRoles = {
    publicId?: number;
    displayName?: string;
    avatarUrl?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
};

export type LobbyRolesResponse = {
    lobbyId?: string;
    members?: Array<LobbyMemberRoles>;
};

export type TransferHostRequest = {
    targetPublicId: number;
};

export type LobbyMember = {
    publicId?: number;
    displayName?: string;
    avatarUrl?: string;
    joinedAt?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
};

export type LobbySnapshot = {
    id?: string;
    mode?: 'RANKED';
    status?: 'OPEN' | 'SEARCHING' | 'CLOSED';
    ownerPublicId?: number;
    maxPlayers?: number;
    members?: Array<LobbyMember>;
    createdAt?: string;
    updatedAt?: string;
};

export type ChampionHoverPayload = {
    playerPublicId?: number;
    champion?: string;
    hoveredAt?: string;
};

export type ChampionSelectionPayload = {
    playerPublicId?: number;
    champion?: string;
    selectedAt?: string;
};

export type GameServerPayload = {
    host?: string;
    port?: number;
    protocol?: string;
    controlHost?: string;
    controlPort?: number;
    controlProtocol?: string;
    controlBaseUrl?: string;
};

export type MatchLobbyPayload = {
    lobbyId?: string;
    players?: Array<MatchPlayerPayload>;
};

export type MatchPlayerPayload = {
    publicId?: number;
    displayName?: string;
    avatarUrl?: string;
    team?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    assignedRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    roleAssignmentSource?: string;
};

export type MatchResponse = {
    matchId?: string;
    mode?: string;
    status?: 'WAITING_FOR_LOBBIES' | 'PENDING_ACCEPTANCE' | 'CHAMPION_SELECTION' | 'READY' | 'CANCELLED' | 'ENDED';
    phase?: 'PENDING_ACCEPTANCE' | 'WARMUP' | 'PICK' | 'READY';
    lobbies?: Array<MatchLobbyPayload>;
    acceptances?: Array<PlayerAcceptancePayload>;
    championSelections?: Array<ChampionSelectionPayload>;
    championHovers?: Array<ChampionHoverPayload>;
    roleAssignments?: Array<MatchRoleAssignmentPayload>;
    gameServer?: GameServerPayload;
    createdAt?: string;
    updatedAt?: string;
    serverNow?: string;
    phaseEndsAt?: string;
};

export type MatchRoleAssignmentPayload = {
    publicId?: number;
    team?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    assignedRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    source?: string;
};

export type PlayerAcceptancePayload = {
    playerPublicId?: number;
    status?: 'PENDING' | 'ACCEPTED';
};

export type ChatEventRequest = {
    eventType?: string;
    recipients?: Array<number>;
    payload?: unknown;
};

export type DesktopSessionConflictEvent = {
    publicId?: number;
    userId?: string;
    sessionId?: string;
    deviceType?: string;
    sourceIp?: string;
    userAgent?: string;
    reason?: string;
    occurredAt?: string;
};

export type ChampionSelectRequest = {
    champion: string;
};

export type MatchChampionSelectionLeaveRequest = {
    status: 'DISCONNECTED' | 'QUIT' | 'LEAVE';
};

export type ChampionHoverRequest = {
    champion: string;
};

export type MatchChampionHoversResponse = {
    matchId?: string;
    hovers?: Array<ChampionHoverPayload>;
};

export type InvitePlayerRequest = {
    targetPublicId: number;
};

export type LobbyInvitation = {
    lobbyId?: string;
    mode?: 'RANKED';
    inviteePublicId?: number;
    inviters?: Array<LobbyMember>;
    lobby?: LobbySnapshot;
    updatedAt?: string;
};

export type RankedSearchRequest = {
    lobbyId: string;
};

export type RankedSearchStarted = {
    lobbyId?: string;
    mode?: 'RANKED';
    playerCount?: number;
    startedAt?: string;
};

export type FriendRequest = {
    id?: number;
    requester?: FriendUser;
    addressee?: FriendUser;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type FriendUser = {
    publicId?: number;
    displayName?: string;
    email?: string;
    avatarUrl?: string;
    avatarRightsConsented?: boolean;
    avatarRightsConsentedAt?: string;
};

export type OnlineUserStatusSnapshot = {
    publicId?: number;
    displayName?: string;
    status?: 'OFFLINE' | 'ONLINE' | 'AFK' | 'IN_LOBBY' | 'IN_QUEUE' | 'CHAMPION_SELECTION' | 'IN_GAME' | 'SPECTATE';
    mode?: string;
    updatedAt?: string;
};

export type OnlineUsersResponse = {
    users?: Array<OnlineUserStatusSnapshot>;
    page?: number;
    limit?: number;
    total?: number;
    totalPages?: number;
};

export type FriendUserStatusesResponse = {
    statuses?: Array<UserStatusSnapshot>;
};

export type SseEmitter = {
    timeout?: number;
};

export type AuthUser = {
    subject?: string;
    publicId?: number;
    email?: string;
    preferredUsername?: string;
    displayName?: string;
    tagId?: string;
    avatarUrl?: string;
};

export type FriendRequests = {
    incoming?: Array<FriendRequest>;
    outgoing?: Array<FriendRequest>;
};

export type Friends = {
    friends?: Array<FriendUser>;
};

export type LiveBootstrapResponse = {
    user?: AuthUser;
    userStatus?: UserStatusSnapshot;
    friends?: Friends;
    friendRequests?: FriendRequests;
    friendStatuses?: FriendUserStatusesResponse;
    openFriendLobbies?: Array<LobbySnapshot>;
    lobbyInvitations?: Array<LobbyInvitation>;
};

export type MatchRoleAssignmentPlayerRequest = {
    publicId: number;
    team?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
};

export type MatchRoleAssignmentsRequest = {
    players: Array<MatchRoleAssignmentPlayerRequest>;
};

export type MatchRoleAssignmentResponse = {
    publicId?: number;
    team?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    assignedRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    source?: 'PRIMARY' | 'SECONDARY' | 'AUTOFILL';
};

export type MatchRoleAssignmentsResponse = {
    matchId?: string;
    assignments?: Array<MatchRoleAssignmentResponse>;
};

export type ChampionHoverResponse = {
    playerPublicId?: number;
    champion?: string;
    hoveredAt?: string;
};

export type ChampionSelectionResponse = {
    playerPublicId?: number;
    champion?: string;
    selectedAt?: string;
};

export type GameServerResponse = {
    host?: string;
    port?: number;
    protocol?: string;
    controlHost?: string;
    controlPort?: number;
    controlProtocol?: string;
    controlBaseUrl?: string;
};

export type MatchLobbyResponse = {
    lobbyId?: string;
    players?: Array<MatchPlayerResponse>;
};

export type MatchPlayerResponse = {
    publicId?: number;
    displayName?: string;
    avatarUrl?: string;
    team?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    assignedRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    roleAssignmentSource?: 'PRIMARY' | 'SECONDARY' | 'AUTOFILL';
};

export type PlayerAcceptanceResponse = {
    playerPublicId?: number;
    status?: 'PENDING' | 'ACCEPTED';
};

export type ChampionSelectionRequest = {
    playerPublicId: number;
    champion: string;
};

export type MatchDecisionRequest = {
    playerPublicId: number;
    decision: 'ACCEPTED' | 'DECLINED';
};

export type MatchPlayerRequest = {
    publicId: number;
    displayName?: string;
    avatarUrl?: string;
    primaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    secondaryRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
};

export type MatchSearchRequest = {
    lobbyId: string;
    mode: string;
    players: Array<MatchPlayerRequest>;
};

export type MatchSearchResponse = {
    status?: 'WAITING_FOR_LOBBIES' | 'PENDING_ACCEPTANCE' | 'CHAMPION_SELECTION' | 'READY' | 'CANCELLED' | 'ENDED';
    match?: ApiMatchResponse;
};

export type MatchRosterPlayerResponse = {
    publicId?: number;
    displayName?: string;
    avatarUrl?: string;
    team?: string;
    assignedRole?: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
    roleAssignmentSource?: 'PRIMARY' | 'SECONDARY' | 'AUTOFILL';
};

export type MatchRosterResponse = {
    matchId?: string;
    mode?: string;
    team?: string;
    players?: Array<MatchRosterPlayerResponse>;
};

export type MatchAbortResponse = {
    removed?: boolean;
    cancelledMatch?: ApiMatchResponse;
};

export type ApiMatchResponse = {
    matchId?: string;
    mode?: string;
    status?: 'WAITING_FOR_LOBBIES' | 'PENDING_ACCEPTANCE' | 'CHAMPION_SELECTION' | 'READY' | 'CANCELLED' | 'ENDED';
    phase?: 'PENDING_ACCEPTANCE' | 'WARMUP' | 'PICK' | 'READY';
    lobbies?: Array<MatchLobbyResponse>;
    acceptances?: Array<PlayerAcceptanceResponse>;
    championSelections?: Array<ChampionSelectionResponse>;
    championHovers?: Array<ChampionHoverResponse>;
    roleAssignments?: Array<MatchRoleAssignmentResponse>;
    gameServer?: GameServerResponse;
    createdAt?: string;
    updatedAt?: string;
    serverNow?: string;
    phaseEndsAt?: string;
};

export type ApiChampionHoverRequest = {
    playerPublicId: number;
    champion: string;
};

export type ApiMatchChampionHoversResponse = {
    matchId?: string;
    hovers?: Array<ChampionHoverResponse>;
};

export type MarkRoomReadRequest = {
    messageId?: string;
};

export type ChatMessageResponse = {
    messageId?: string;
    roomId?: string;
    senderPublicId?: number;
    content?: string;
    createdAt?: string;
};

export type ChatRoomResponse = {
    roomId?: string;
    type?: 'PRIVATE' | 'LOBBY' | 'TEAM' | 'INGAME';
    contextId?: string;
    participantPublicIds?: Array<number>;
    createdAt?: string;
    updatedAt?: string;
    lastMessage?: ChatMessageResponse;
    unreadCount?: number;
    lastReadAt?: string;
};

export type SendMessageRequest = {
    content: string;
};

export type ChatMessagesResponse = {
    messages?: Array<ChatMessageResponse>;
};

export type UpdateUsernameData = {
    body: UpdateUsernameRequest;
    path?: never;
    query?: never;
    url: '/api/me/username';
};

export type UpdateUsernameResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type UpdateUsernameResponse = UpdateUsernameResponses[keyof UpdateUsernameResponses];

export type UpdateTagIdData = {
    body: UpdateTagIdRequest;
    path?: never;
    query?: never;
    url: '/api/me/tag-id';
};

export type UpdateTagIdResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type UpdateTagIdResponse = UpdateTagIdResponses[keyof UpdateTagIdResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: ClientSettingsResponse;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: UpdateClientSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: ClientSettingsResponse;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type ListFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/settings/folders';
};

export type ListFoldersResponses = {
    /**
     * OK
     */
    200: Array<ClientSettingsFolderResponse>;
};

export type ListFoldersResponse = ListFoldersResponses[keyof ListFoldersResponses];

export type ReplaceFoldersData = {
    body: Array<ClientSettingsFolderRequest>;
    path?: never;
    query?: never;
    url: '/api/me/settings/folders';
};

export type ReplaceFoldersResponses = {
    /**
     * OK
     */
    200: Array<ClientSettingsFolderResponse>;
};

export type ReplaceFoldersResponse = ReplaceFoldersResponses[keyof ReplaceFoldersResponses];

export type DeleteFolderData = {
    body?: never;
    path: {
        folderName: string;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}';
};

export type DeleteFolderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetFolderData = {
    body?: never;
    path: {
        folderName: string;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}';
};

export type GetFolderResponses = {
    /**
     * OK
     */
    200: ClientSettingsFolderResponse;
};

export type GetFolderResponse = GetFolderResponses[keyof GetFolderResponses];

export type UpsertFolderData = {
    body: ClientSettingsFolderUpsertRequest;
    path: {
        folderName: string;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}';
};

export type UpsertFolderResponses = {
    /**
     * OK
     */
    200: ClientSettingsFolderResponse;
};

export type UpsertFolderResponse = UpsertFolderResponses[keyof UpsertFolderResponses];

export type RenameFolderData = {
    body: ClientSettingsFolderRenameRequest;
    path: {
        folderName: string;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}/rename';
};

export type RenameFolderResponses = {
    /**
     * OK
     */
    200: ClientSettingsFolderResponse;
};

export type RenameFolderResponse = RenameFolderResponses[keyof RenameFolderResponses];

export type ReorderFoldersData = {
    body: ClientSettingsFolderOrderRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings/folders/order';
};

export type ReorderFoldersResponses = {
    /**
     * OK
     */
    200: Array<ClientSettingsFolderResponse>;
};

export type ReorderFoldersResponse = ReorderFoldersResponses[keyof ReorderFoldersResponses];

export type SetLevelData = {
    body: UpdateLevelRequest;
    path?: never;
    query?: never;
    url: '/api/me/level';
};

export type SetLevelResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type SetLevelResponse = SetLevelResponses[keyof SetLevelResponses];

export type DeleteByEmailData = {
    body: DeleteUserRequest;
    path?: never;
    query?: never;
    url: '/api/public/register';
};

export type DeleteByEmailResponses = {
    /**
     * OK
     */
    200: RegistrationResponse;
};

export type DeleteByEmailResponse = DeleteByEmailResponses[keyof DeleteByEmailResponses];

export type RegisterData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/api/public/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: RegistrationResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RemoveFriendFromFolderData = {
    body?: never;
    path: {
        folderName: string;
        friendPublicId: number;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}/friends/{friendPublicId}';
};

export type RemoveFriendFromFolderResponses = {
    /**
     * OK
     */
    200: ClientSettingsFolderResponse;
};

export type RemoveFriendFromFolderResponse = RemoveFriendFromFolderResponses[keyof RemoveFriendFromFolderResponses];

export type AddFriendToFolderData = {
    body?: never;
    path: {
        folderName: string;
        friendPublicId: number;
    };
    query?: never;
    url: '/api/me/settings/folders/{folderName}/friends/{friendPublicId}';
};

export type AddFriendToFolderResponses = {
    /**
     * OK
     */
    200: ClientSettingsFolderResponse;
};

export type AddFriendToFolderResponse = AddFriendToFolderResponses[keyof AddFriendToFolderResponses];

export type IncreaseLevelData = {
    body: IncreaseLevelRequest;
    path?: never;
    query?: never;
    url: '/api/me/level/increase';
};

export type IncreaseLevelResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type IncreaseLevelResponse = IncreaseLevelResponses[keyof IncreaseLevelResponses];

export type GetAvatarRightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/avatar-rights';
};

export type GetAvatarRightsResponses = {
    /**
     * OK
     */
    200: AvatarRightsConsentResponse;
};

export type GetAvatarRightsResponse = GetAvatarRightsResponses[keyof GetAvatarRightsResponses];

export type ConfirmAvatarRightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/avatar-rights';
};

export type ConfirmAvatarRightsResponses = {
    /**
     * OK
     */
    200: AvatarRightsConsentResponse;
};

export type ConfirmAvatarRightsResponse = ConfirmAvatarRightsResponses[keyof ConfirmAvatarRightsResponses];

export type ListRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/friends/requests';
};

export type ListRequestsResponses = {
    /**
     * OK
     */
    200: FriendRequestsResponse;
};

export type ListRequestsResponse = ListRequestsResponses[keyof ListRequestsResponses];

export type SendRequestData = {
    body: FriendActionRequest;
    path?: never;
    query?: never;
    url: '/api/friends/requests';
};

export type SendRequestResponses = {
    /**
     * OK
     */
    200: FriendRequestResponse;
};

export type SendRequestResponse = SendRequestResponses[keyof SendRequestResponses];

export type DeclineRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/friends/requests/{requestId}/decline';
};

export type DeclineRequestResponses = {
    /**
     * OK
     */
    200: FriendRequestResponse;
};

export type DeclineRequestResponse = DeclineRequestResponses[keyof DeclineRequestResponses];

export type AcceptRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/friends/requests/{requestId}/accept';
};

export type AcceptRequestResponses = {
    /**
     * OK
     */
    200: FriendRequestResponse;
};

export type AcceptRequestResponse = AcceptRequestResponses[keyof AcceptRequestResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type HeartbeatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session/heartbeat';
};

export type HeartbeatResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PublicClientSettingsData = {
    body?: never;
    path: {
        publicId: number;
    };
    query?: never;
    url: '/api/users/{publicId}/settings-summary';
};

export type PublicClientSettingsResponses = {
    /**
     * OK
     */
    200: PublicClientSettingsResponse;
};

export type PublicClientSettingsResponse2 = PublicClientSettingsResponses[keyof PublicClientSettingsResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/api/users/search';
};

export type SearchResponses = {
    /**
     * OK
     */
    200: UserSearchResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type UsersByPublicIdsData = {
    body?: never;
    path?: never;
    query: {
        publicIds: Array<number>;
    };
    url: '/api/users/by-public-ids';
};

export type UsersByPublicIdsResponses = {
    /**
     * OK
     */
    200: PublicUsersResponse;
};

export type UsersByPublicIdsResponse = UsersByPublicIdsResponses[keyof UsersByPublicIdsResponses];

export type LoginOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/login-options';
};

export type LoginOptionsResponses = {
    /**
     * OK
     */
    200: LoginOptionsResponse;
};

export type LoginOptionsResponse2 = LoginOptionsResponses[keyof LoginOptionsResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListFriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/friends';
};

export type ListFriendsResponses = {
    /**
     * OK
     */
    200: FriendsResponse;
};

export type ListFriendsResponse = ListFriendsResponses[keyof ListFriendsResponses];

export type LoginAttemptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session/login-attempts';
};

export type LoginAttemptsResponses = {
    /**
     * OK
     */
    200: LoginAttemptResponse;
};

export type LoginAttemptsResponse = LoginAttemptsResponses[keyof LoginAttemptsResponses];

export type DebugData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/debug';
};

export type DebugResponses = {
    /**
     * OK
     */
    200: AuthDebugResponse;
};

export type DebugResponse = DebugResponses[keyof DebugResponses];

export type RemoveFriendData = {
    body?: never;
    path: {
        friendPublicId: number;
    };
    query?: never;
    url: '/api/friends/{friendPublicId}';
};

export type RemoveFriendResponses = {
    /**
     * OK
     */
    200: FriendRequestResponse;
};

export type RemoveFriendResponse = RemoveFriendResponses[keyof RemoveFriendResponses];

export type RevokeRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/friends/requests/{requestId}';
};

export type RevokeRequestResponses = {
    /**
     * OK
     */
    200: FriendRequestResponse;
};

export type RevokeRequestResponse = RevokeRequestResponses[keyof RevokeRequestResponses];

export type UserStatusMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-status/me';
};

export type UserStatusMeResponses = {
    /**
     * OK
     */
    200: UserStatusSnapshot;
};

export type UserStatusMeResponse = UserStatusMeResponses[keyof UserStatusMeResponses];

export type UpdateMeData = {
    body: UpdateUserStatusRequest;
    path?: never;
    query?: never;
    url: '/api/user-status/me';
};

export type UpdateMeResponses = {
    /**
     * OK
     */
    200: UserStatusSnapshot;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type UpdateRolesData = {
    body: UpdateLobbyRolesRequest;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/members/me/roles';
};

export type UpdateRolesResponses = {
    /**
     * OK
     */
    200: LobbyRolesResponse;
};

export type UpdateRolesResponse = UpdateRolesResponses[keyof UpdateRolesResponses];

export type TransferHostData = {
    body: TransferHostRequest;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/host';
};

export type TransferHostResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type TransferHostResponse = TransferHostResponses[keyof TransferHostResponses];

export type EndMatchData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/live/matches/{matchId}/ended';
};

export type EndMatchResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type EndMatchResponse = EndMatchResponses[keyof EndMatchResponses];

export type PublishChatEventsData = {
    body: ChatEventRequest;
    path?: never;
    query?: never;
    url: '/internal/live/chat-events';
};

export type PublishChatEventsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SessionConflictData = {
    body: DesktopSessionConflictEvent;
    path?: never;
    query?: never;
    url: '/internal/live/auth-events/session-conflict';
};

export type SessionConflictResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeclineData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/decline';
};

export type DeclineResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type DeclineResponse = DeclineResponses[keyof DeclineResponses];

export type SelectChampionData = {
    body: ChampionSelectRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-selection';
};

export type SelectChampionResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type SelectChampionResponse = SelectChampionResponses[keyof SelectChampionResponses];

export type MarkChampionsReadyData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-selection/ready';
};

export type MarkChampionsReadyResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type MarkChampionsReadyResponse = MarkChampionsReadyResponses[keyof MarkChampionsReadyResponses];

export type NotifyChampionSelectionLeftData = {
    body: MatchChampionSelectionLeaveRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-selection/leave';
};

export type NotifyChampionSelectionLeftResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type NotifyChampionSelectionLeftResponse = NotifyChampionSelectionLeftResponses[keyof NotifyChampionSelectionLeftResponses];

export type ClearChampionHoverData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-hover';
};

export type ClearChampionHoverResponses = {
    /**
     * OK
     */
    200: MatchChampionHoversResponse;
};

export type ClearChampionHoverResponse = ClearChampionHoverResponses[keyof ClearChampionHoverResponses];

export type HoverChampionData = {
    body: ChampionHoverRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-hover';
};

export type HoverChampionResponses = {
    /**
     * OK
     */
    200: MatchChampionHoversResponse;
};

export type HoverChampionResponse = HoverChampionResponses[keyof HoverChampionResponses];

export type AcceptData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/accept';
};

export type AcceptResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type AcceptResponse = AcceptResponses[keyof AcceptResponses];

export type JoinLobbyData = {
    body?: never;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/join';
};

export type JoinLobbyResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type JoinLobbyResponse = JoinLobbyResponses[keyof JoinLobbyResponses];

export type InviteData = {
    body: InvitePlayerRequest;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/invites';
};

export type InviteResponses = {
    /**
     * OK
     */
    200: LobbyInvitation;
};

export type InviteResponse = InviteResponses[keyof InviteResponses];

export type CreateRankedLobbyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/lobbies/ranked';
};

export type CreateRankedLobbyResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type CreateRankedLobbyResponse = CreateRankedLobbyResponses[keyof CreateRankedLobbyResponses];

export type AbortRankedSearchData = {
    body: RankedSearchRequest;
    path?: never;
    query?: never;
    url: '/api/lobbies/ranked/search';
};

export type AbortRankedSearchResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type AbortRankedSearchResponse = AbortRankedSearchResponses[keyof AbortRankedSearchResponses];

export type SearchRankedData = {
    body: RankedSearchRequest;
    path?: never;
    query?: never;
    url: '/api/lobbies/ranked/search';
};

export type SearchRankedResponses = {
    /**
     * OK
     */
    200: RankedSearchStarted;
};

export type SearchRankedResponse = SearchRankedResponses[keyof SearchRankedResponses];

export type LiveHeartbeatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/live/heartbeat';
};

export type LiveHeartbeatResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LiveSendRequestData = {
    body: FriendActionRequest;
    path?: never;
    query?: never;
    url: '/api/live/friends/requests';
};

export type LiveSendRequestResponses = {
    /**
     * OK
     */
    200: FriendRequest;
};

export type LiveSendRequestResponse = LiveSendRequestResponses[keyof LiveSendRequestResponses];

export type LiveDeclineRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/live/friends/requests/{requestId}/decline';
};

export type LiveDeclineRequestResponses = {
    /**
     * OK
     */
    200: FriendRequest;
};

export type LiveDeclineRequestResponse = LiveDeclineRequestResponses[keyof LiveDeclineRequestResponses];

export type LiveAcceptRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/live/friends/requests/{requestId}/accept';
};

export type LiveAcceptRequestResponses = {
    /**
     * OK
     */
    200: FriendRequest;
};

export type LiveAcceptRequestResponse = LiveAcceptRequestResponses[keyof LiveAcceptRequestResponses];

export type OnlineData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/users/online';
};

export type OnlineResponses = {
    /**
     * OK
     */
    200: OnlineUsersResponse;
};

export type OnlineResponse = OnlineResponses[keyof OnlineResponses];

export type FriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-status/friends';
};

export type FriendsResponses = {
    /**
     * OK
     */
    200: FriendUserStatusesResponse;
};

export type FriendsResponse2 = FriendsResponses[keyof FriendsResponses];

export type RolesData = {
    body?: never;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/roles';
};

export type RolesResponses = {
    /**
     * OK
     */
    200: LobbyRolesResponse;
};

export type RolesResponse = RolesResponses[keyof RolesResponses];

export type InvitationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/lobbies/invitations';
};

export type InvitationsResponses = {
    /**
     * OK
     */
    200: Array<LobbyInvitation>;
};

export type InvitationsResponse = InvitationsResponses[keyof InvitationsResponses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/live/events';
};

export type EventsResponses = {
    /**
     * OK
     */
    200: SseEmitter;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type BootstrapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/live/bootstrap';
};

export type BootstrapResponses = {
    /**
     * OK
     */
    200: LiveBootstrapResponse;
};

export type BootstrapResponse = BootstrapResponses[keyof BootstrapResponses];

export type CancelChampionPhaseData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/matches/{matchId}/champion-phase';
};

export type CancelChampionPhaseResponses = {
    /**
     * OK
     */
    200: MatchResponse;
};

export type CancelChampionPhaseResponse = CancelChampionPhaseResponses[keyof CancelChampionPhaseResponses];

export type KickMemberData = {
    body?: never;
    path: {
        lobbyId: string;
        memberPublicId: number;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/members/{memberPublicId}';
};

export type KickMemberResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type KickMemberResponse = KickMemberResponses[keyof KickMemberResponses];

export type LeaveLobbyData = {
    body?: never;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/lobbies/{lobbyId}/members/me';
};

export type LeaveLobbyResponses = {
    /**
     * OK
     */
    200: LobbySnapshot;
};

export type LeaveLobbyResponse = LeaveLobbyResponses[keyof LeaveLobbyResponses];

export type LiveRemoveFriendData = {
    body?: never;
    path: {
        friendPublicId: number;
    };
    query?: never;
    url: '/api/live/friends/{friendPublicId}';
};

export type LiveRemoveFriendResponses = {
    /**
     * OK
     */
    200: FriendRequest;
};

export type LiveRemoveFriendResponse = LiveRemoveFriendResponses[keyof LiveRemoveFriendResponses];

export type LiveRevokeRequestData = {
    body?: never;
    path: {
        requestId: number;
    };
    query?: never;
    url: '/api/live/friends/requests/{requestId}';
};

export type LiveRevokeRequestResponses = {
    /**
     * OK
     */
    200: FriendRequest;
};

export type LiveRevokeRequestResponse = LiveRevokeRequestResponses[keyof LiveRevokeRequestResponses];

export type AssignRolesData = {
    body: MatchRoleAssignmentsRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/role-assignments';
};

export type AssignRolesResponses = {
    /**
     * OK
     */
    200: MatchRoleAssignmentsResponse;
};

export type AssignRolesResponse = AssignRolesResponses[keyof AssignRolesResponses];

export type EndMatchDuplicateData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/ended';
};

export type EndMatchDuplicateResponses = {
    /**
     * OK
     */
    200: ApiMatchResponse;
};

export type EndMatchDuplicateResponse = EndMatchDuplicateResponses[keyof EndMatchDuplicateResponses];

export type SelectChampionDuplicateData = {
    body: ChampionSelectionRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/champion-selections';
};

export type SelectChampionDuplicateResponses = {
    /**
     * OK
     */
    200: ApiMatchResponse;
};

export type SelectChampionDuplicateResponse = SelectChampionDuplicateResponses[keyof SelectChampionDuplicateResponses];

export type MarkChampionsReadyDuplicateData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/champion-selections/ready';
};

export type MarkChampionsReadyDuplicateResponses = {
    /**
     * OK
     */
    200: ApiMatchResponse;
};

export type MarkChampionsReadyDuplicateResponse = MarkChampionsReadyDuplicateResponses[keyof MarkChampionsReadyDuplicateResponses];

export type HoverChampionDuplicateData = {
    body: ApiChampionHoverRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/champion-hovers';
};

export type HoverChampionDuplicateResponses = {
    /**
     * OK
     */
    200: ApiMatchChampionHoversResponse;
};

export type HoverChampionDuplicateResponse = HoverChampionDuplicateResponses[keyof HoverChampionDuplicateResponses];

export type DecideData = {
    body: MatchDecisionRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/acceptances';
};

export type DecideResponses = {
    /**
     * OK
     */
    200: ApiMatchResponse;
};

export type DecideResponse = DecideResponses[keyof DecideResponses];

export type StartSearchData = {
    body: MatchSearchRequest;
    path?: never;
    query?: never;
    url: '/internal/matches/searches';
};

export type StartSearchResponses = {
    /**
     * OK
     */
    200: MatchSearchResponse;
};

export type StartSearchResponse = StartSearchResponses[keyof StartSearchResponses];

export type GetData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}';
};

export type GetResponses = {
    /**
     * OK
     */
    200: ApiMatchResponse;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type RosterData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: {
        team?: string;
    };
    url: '/internal/matches/{matchId}/players';
};

export type RosterResponses = {
    /**
     * OK
     */
    200: MatchRosterResponse;
};

export type RosterResponse = RosterResponses[keyof RosterResponses];

export type TemporaryMatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/internal/matches/temporary';
};

export type TemporaryMatchesResponses = {
    /**
     * OK
     */
    200: Array<ApiMatchResponse>;
};

export type TemporaryMatchesResponse = TemporaryMatchesResponses[keyof TemporaryMatchesResponses];

export type CancelChampionPhaseDuplicateData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/internal/matches/{matchId}/champion-phase';
};

export type CancelChampionPhaseDuplicateResponses = {
    /**
     * OK
     */
    200: MatchAbortResponse;
};

export type CancelChampionPhaseDuplicateResponse = CancelChampionPhaseDuplicateResponses[keyof CancelChampionPhaseDuplicateResponses];

export type ClearChampionHoverDuplicateData = {
    body?: never;
    path: {
        matchId: string;
        playerPublicId: number;
    };
    query?: never;
    url: '/internal/matches/{matchId}/champion-hovers/{playerPublicId}';
};

export type ClearChampionHoverDuplicateResponses = {
    /**
     * OK
     */
    200: ApiMatchChampionHoversResponse;
};

export type ClearChampionHoverDuplicateResponse = ClearChampionHoverDuplicateResponses[keyof ClearChampionHoverDuplicateResponses];

export type AbortSearchData = {
    body?: never;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/internal/matches/searches/{lobbyId}';
};

export type AbortSearchResponses = {
    /**
     * OK
     */
    200: MatchAbortResponse;
};

export type AbortSearchResponse = AbortSearchResponses[keyof AbortSearchResponses];

export type ClearRetentionHoldData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/internal/chats/rooms/{roomId}/retention-hold';
};

export type ClearRetentionHoldResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ClearRetentionHoldResponse = ClearRetentionHoldResponses[keyof ClearRetentionHoldResponses];

export type SetRetentionHoldData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/internal/chats/rooms/{roomId}/retention-hold';
};

export type SetRetentionHoldResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetRetentionHoldResponse = SetRetentionHoldResponses[keyof SetRetentionHoldResponses];

export type MarkReadData = {
    body?: MarkRoomReadRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/chats/{roomId}/read';
};

export type MarkReadResponses = {
    /**
     * OK
     */
    200: ChatRoomResponse;
};

export type MarkReadResponse = MarkReadResponses[keyof MarkReadResponses];

export type SendPrivateData = {
    body: SendMessageRequest;
    path: {
        targetPublicId: number;
    };
    query?: never;
    url: '/api/chats/private/{targetPublicId}/messages';
};

export type SendPrivateResponses = {
    /**
     * OK
     */
    200: ChatMessageResponse;
};

export type SendPrivateResponse = SendPrivateResponses[keyof SendPrivateResponses];

export type SendTeamMessageData = {
    body: SendMessageRequest;
    path: {
        matchId: string;
        team: string;
    };
    query?: never;
    url: '/api/chats/matches/{matchId}/teams/{team}/messages';
};

export type SendTeamMessageResponses = {
    /**
     * OK
     */
    200: ChatMessageResponse;
};

export type SendTeamMessageResponse = SendTeamMessageResponses[keyof SendTeamMessageResponses];

export type SendIngameMessageData = {
    body: SendMessageRequest;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/chats/matches/{matchId}/messages';
};

export type SendIngameMessageResponses = {
    /**
     * OK
     */
    200: ChatMessageResponse;
};

export type SendIngameMessageResponse = SendIngameMessageResponses[keyof SendIngameMessageResponses];

export type SendLobbyMessageData = {
    body: SendMessageRequest;
    path: {
        lobbyId: string;
    };
    query?: never;
    url: '/api/chats/lobbies/{lobbyId}/messages';
};

export type SendLobbyMessageResponses = {
    /**
     * OK
     */
    200: ChatMessageResponse;
};

export type SendLobbyMessageResponse = SendLobbyMessageResponses[keyof SendLobbyMessageResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type ListRoomsResponses = {
    /**
     * OK
     */
    200: Array<ChatRoomResponse>;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type DeleteRoomData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/chats/{roomId}';
};

export type DeleteRoomResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoomResponse = DeleteRoomResponses[keyof DeleteRoomResponses];

export type GetRoomData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/chats/{roomId}';
};

export type GetRoomResponses = {
    /**
     * OK
     */
    200: ChatRoomResponse;
};

export type GetRoomResponse = GetRoomResponses[keyof GetRoomResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: {
        limit?: number;
        before?: string;
    };
    url: '/api/chats/{roomId}/messages';
};

export type ListMessagesResponses = {
    /**
     * OK
     */
    200: ChatMessagesResponse;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type ChatsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats/events';
};

export type ChatsEventsResponses = {
    /**
     * OK
     */
    200: SseEmitter;
};

export type ChatsEventsResponse = ChatsEventsResponses[keyof ChatsEventsResponses];

export type DeleteRoom1Data = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/chats/rooms/{roomId}';
};

export type DeleteRoom1Responses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoom1Response = DeleteRoom1Responses[keyof DeleteRoom1Responses];
