apiVersion: v1
kind: ConfigMap
metadata:
  name: mira-website-runtime
data:
  runtime.json: |
    {
      "environment": "prod",
      "apiBaseUrl": "https://api.tilt-us.com",
      "keycloakBaseUrl": "https://api.tilt-us.com/keycloak",
      "keycloakRealm": "mira",
      "keycloakClientId": "mira-web",
      "keycloakPasswordClientId": "mira-web"
    }
