apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mira-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev.tilt-us.com
      secretName: mira-website-dev-tls
  rules:
    - host: dev.tilt-us.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mira-website
                port:
                  name: http
